### ISSUE TITLE
Question: single cell CNV data

### ISSUE THREAD

**Issue by rmvpaeme** [raphael-group/CNTMD#3]
Would this method work on single cell CNV data (> 500 cells)?

**Comment by simozacca** [comment]
CNT-MD is a method designed to work with DNA bulk-sequencing data, the standard sequencing for cancer (and non) sequencing studies. CNT-MD is needed for this kind of data because you are sequencing millions of different cells which may have different copy-number aberrations; as such, you need to deconvolve the data to identify different subpopulations of cells in the mixture. CNT-MD simultaneously infers the tumor evolution to constrain this deconvolution (you can find more details in the related publication).

If you have CNV data for single cells and you aim to infer the tumor evolution in terms of these data, you do not need the deconvolution and you can do this with another method from our group, that is CNT-ILP:

    https://github.com/raphael-group/CNT-ILP

CNT-ILP takes in input copy-number profiles (that you obtain from your single-cell CNV data and correspond to the leaves of the phylogeny) and infers the phylogenetic tree that describes the corresponding tumor evolution.
However, CNT-ILP will not scale to a phylogenetic tree with >500 leaves (that may also not be informative when many cells are very similar).
Thus, you need to cluster the cells first and then run CNT-ILP.

You can also ask specific questions about CNT-ILP on the related github page,
Please let me know if you have further questions, 

Best
